### ISSUE TITLE
Custom fan speed curve applies only to 1 fan on Gigabyte Gaming OC RTX 3080 card

### ISSUE THREAD

**Issue by Pivoo** [Lurkki14/tuxclocker#44] opened 2021-01-21 09:38 UTC
All RTX 3080 have 3 fans, I don't know how other companies 3080 cards have it set up in BIOS, but from what i see, the Gigabyte Gaming OC 3080 has 2 fan speed sliders in the NVIDIA X Server Settings (Thermal Settings).

Normally it looks like this:
http://2.bp.blogspot.com/-TXEz3Gpyqk0/VUtEZ1nxS1I/AAAAAAAANNw/DRldQLj1V5w/s1600/thermal-settings-fanspeed.jpg

For the mentioned card, There are 2 fan speeds:
Fan 0 Speed
Fan 1 Speed

The custom curve applies only to Fan 1 Speed, which results in only 1 fan of 3 spinning. I guess Fan 0 Speed is setting the speed of remaining 2 fans. Custom curve should apply to both Fan Speeds.

**Comment by Lurkki14** [comment] 2021-01-28 11:42
Duplicate of https://github.com/Lurkki14/tuxclocker/issues/24

**Closed by Lurkki14** 2021-01-28 11:42 UTC
