### ISSUE TITLE
Ninja build failure

### ISSUE THREAD

**Issue by xcoldfyrex** [Lurkki14/tuxclocker#56] opened 2023-09-28 14:56 UTC
Ninja fails at 
```[52/53] Compiling C++ object src/tuxclocker-qt/tuxclocker-qt.p/widgets_FlagEditor.cpp.o
FAILED: src/tuxclocker-qt/tuxclocker-qt.p/widgets_FlagEditor.cpp.o
ccache c++ -Isrc/tuxclocker-qt/tuxclocker-qt.p -Isrc/tuxclocker-qt -I../src/tuxclocker-qt -I../src/include -I../src/include/deps -I../src/tuxclocker-qt/data -I../src/tuxclocker-qt/widgets -I../src/include/deps/FunctionalPlus/include -I../src/include/deps/patterns/include/mpark -I/usr/include/qt5/QtDBus -I/usr/include/qt5 -I/usr/include/qt5/QtCore -I/usr/include/qt5/QtCharts -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtWidgets -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++17 -O0 -g -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -fPIC -MD -MQ src/tuxclocker-qt/tuxclocker-qt.p/widgets_FlagEditor.cpp.o -MF src/tuxclocker-qt/tuxclocker-qt.p/widgets_FlagEditor.cpp.o.d -o src/tuxclocker-qt/tuxclocker-qt.p/widgets_FlagEditor.cpp.o -c ../src/tuxclocker-qt/widgets/FlagEditor.cpp
In file included from ../src/include/deps/FunctionalPlus/include/fplus/generate.hpp:10,
                 from ../src/include/deps/FunctionalPlus/include/fplus/container_properties.hpp:11,
                 from ../src/include/deps/FunctionalPlus/include/fplus/fplus.hpp:12,
                 from ../src/tuxclocker-qt/widgets/FlagEditor.hpp:7,
                 from ../src/tuxclocker-qt/widgets/FlagEditor.cpp:1:
../src/include/deps/FunctionalPlus/include/fplus/numeric.hpp: In function ‘Out fplus::integral_cast_throw(X)’:
../src/include/deps/FunctionalPlus/include/fplus/numeric.hpp:237:30: error: ‘int64_t’ in namespace ‘std’ does not name a type
  237 |         if (static_cast<std::int64_t>(x) <
      |                              ^~~~~~~
```
[build.log](https://github.com/Lurkki14/tuxclocker/files/12750964/build.log)
I've tried removing meson build options.

**Comment by Lurkki14** [comment] 2023-09-28 15:01
This is a duplicate of https://github.com/Lurkki14/tuxclocker/issues/55 , it was just a little hard to see since the output was inside a file that wasn't embedded. I updated that issue with the relevant output.

**Closed by Lurkki14** 2023-09-28 15:01 UTC

**Comment by Lurkki14** [comment] 2023-09-28 15:33
@xcoldfyrex see https://github.com/Lurkki14/tuxclocker/issues/55#issuecomment-1739546968 for a possible fix
