### ISSUE TITLE
Segmentation fault using AMD GPU on master and pstatetest

### ISSUE THREAD

**Issue by JAicewizard** [Lurkki14/tuxclocker#29] opened 2019-10-04 14:17 UTC
A segmentation fault on startup using arch linux.
Build using the instructions in the readme 

output of tuxclocker
```
QMetaObject::connectSlotsByName: No matching signal for on_newProfile_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_newProfile_closed()
QMetaObject::connectSlotsByName: No matching signal for on_editProfile_closed()
```
output of `coredumpctl -q gdb`
```
           PID: 93071 (tuxclocker)
           UID: 1000 (jaap)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Fri 2019-10-04 16:08:22 CEST (14s ago)
  Command Line: tuxclocker
    Executable: /usr/bin/tuxclocker
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (jaap)
       Boot ID: d1e7cd06bd6146ccb308c4fac85858bb
    Machine ID: a00a8cca7943464b85be63eb81e13107
      Hostname: antergos
       Storage: /var/lib/systemd/coredump/core.tuxclocker.1000.d1e7cd06bd6146ccb308c4fac85858bb.93071.1570198102000000000000.lz4
       Message: Process 93071 (tuxclocker) of user 1000 dumped core.
                
                Stack trace of thread 93071:
                #0  0x000056555560fdf0 n/a (tuxclocker)
                #1  0x000056555557f569 n/a (tuxclocker)
                #2  0x000056555557393e n/a (tuxclocker)
                #3  0x00007efbfd810ee3 __libc_start_main (libc.so.6)
                #4  0x00005655555739fe n/a (tuxclocker)
                
                Stack trace of thread 93072:
                #0  0x00007efbfd8db667 __poll (libc.so.6)
                #1  0x00007efbfd7b5630 n/a (libxcb.so.1)
                #2  0x00007efbfd7b72db xcb_wait_for_event (libxcb.so.1)
                #3  0x00007efbfa71e101 n/a (libQt5XcbQpa.so.5)
                #4  0x00007efbfddb75b0 n/a (libQt5Core.so.5)
                #5  0x00007efbfd78c57f start_thread (libpthread.so.0)
                #6  0x00007efbfd8e60e3 __clone (libc.so.6)
                
                Stack trace of thread 93073:
                #0  0x00007efbfd8db667 __poll (libc.so.6)
                #1  0x00007efbfcc33130 n/a (libglib-2.0.so.0)
                #2  0x00007efbfcc33201 g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007efbfdfdda03 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                #4  0x00007efbfdf844ec _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                #5  0x00007efbfddb6385 _ZN7QThread4execEv (libQt5Core.so.5)
                #6  0x00007efbfa5e6b37 n/a (libQt5DBus.so.5)
                #7  0x00007efbfddb75b0 n/a (libQt5Core.so.5)
                #8  0x00007efbfd78c57f start_thread (libpthread.so.0)
                #9  0x00007efbfd8e60e3 __clone (libc.so.6)

GNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/tuxclocker...
(No debugging symbols found in /usr/bin/tuxclocker)
[New LWP 93071]
[New LWP 93072]
[New LWP 93073]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `tuxclocker'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000056555560fdf0 in ?? ()
```

**Comment by Lurkki14** [comment] 2019-10-05 11:14
run qmake as such: ```qmake CONFIG+=debug rojekti.pro``` to get debug symbols and post the output of that

**Comment by JAicewizard** [comment] 2019-10-05 11:43
Actually this is my bad, the AUR packages write to a different file location than make install.
Building from master does break but building from pstatetest doesn't.

Output running from master:
```
Running as normal user
0
Failed to query amount of GPUs
0 gpus
p��� from nvml
ASSERT failure in QVector<T>::operator[]: "index out of range", file /usr/include/qt/QtCore/qvector.h, line 448
```
on pstateTest it properly detects rx 580.

I don't know the differences is between master and pstatetest but the issue seems fixed in pstatetest.
But maybe add a check for 0 GPUs detected?
Thanks for responding so quickly, its absolutely amazing.

I didn't get any extra information from the coredump with debug enabled but I think the issue has been fixed already.

Have a nice day

**Comment by Lurkki14** [comment] 2019-10-05 11:51
The issue is being fixed in the new branch but both versions work if you're on the correct GPU so this won't be fixed in those branches

**Closed by Lurkki14** 2019-10-05 11:51 UTC

**Comment by borrrsch** [comment] 2019-10-06 16:57
Check the driver you are using. Switching from radeon to amdgpu resolv this issue. Steps about change driver - https://forum.manjaro.org/t/load-amdgpu-drivers/68067/27
