### ISSUE TITLE
Ubuntu 20.04 installation error

### ISSUE THREAD

**Issue by TobiasJu** [Lurkki14/tuxclocker#41] opened 2020-07-28 15:52 UTC
While running make, the following error occured:

```
g++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG_OUTPUT -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/usr/lib -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o main.o main.cpp
In file included from mainwindow.h:26,
                 from main.cpp:18:
nvidia.h:23:10: fatal error: QtX11Extras/QX11Info: No such file or directory
   23 | #include <QtX11Extras/QX11Info>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:466: main.o] Error 1

```

**Comment by Lurkki14** [comment] 2020-07-29 17:49
Duplicate of https://github.com/Lurkki14/tuxclocker/issues/5

**Closed by Lurkki14** 2020-07-29 17:49 UTC
